feat: configurable queue consummation delay
jamesmh/coravel pull request #411
Opened 2024-10-06 09:21 UTC by kmakris23

Issue: #409

2024-12-29 03:16 UTC, kuacci commented on Src/Coravel/Queuing/HostedService/QueuingHost.cs
> +            this._queueOptions = queueOptions;
You have both IConfiguration and QueueOptions here, why not check the appSettings.json value here and  determine which one should be kept?

2025-01-17 19:15 UTC, jamesmh requested changes
Hey, thanks for the contribution!

I have a few improvements that I think will (a) help the code and (b) enable us to add some tests here.

Also, let's add some user documentation for this! In the file `DocsV2/docs/Queuing/README.md` you can add the following to the `Adjusting Consummation Delay` section:

----

Alternatively, you can adjust the consummation delay using `AddQueue`:

```csharp
services.AddQueue(queueOptions => {
    // Consume queue every 5 seconds.
    queueOptions.ConsummationDelay = 5;
});
```

:::tip
`QueueOptions` will take precedence over your configuration file if both are defined.
:::

-----

2025-01-17 19:15 UTC, jamesmh commented on Src/Coravel/Queuing/QueueOptions.cs
> +        public int? ConsummationDelay { get; set; }
Could we add an XML comment here "This determines how often (in seconds) the queue host will consume all pending tasks."

2025-02-02 11:57 UTC, kmakris23 commented
Hi @jamesmh , thanks for your reply. I have updated the code with the required changes. I will be very happy to see it once you have free time.

2025-05-31 21:11 UTC, kmakris23 commented
Hi @HenrikHoyer, thanks for joining. There are pending changes requested by @jamesmh.
I am waiting approval for this PR.

2025-06-30 22:03 UTC, merged